[[
	(load "_common_tl/DIAGRAM/DiagramsInstances.tl")

	////=============================================================================
	//// Generate Tree. this a menu that shows all diagrams....
	////-----------------------------------------------------------------------------
	////(load "_common_tl/DIAGRAM/DiagramsTree.tl")
	////(load "_common_tl/DIAGRAM/TreeTitle.tl")
	////(load "_common_tl/DIAGRAM/CollapsedTree.tl")
]]