//// Purpose: Generates html files for the table charts
//// loaded by: TL/CORE/GenerateReport
(load "HTML/TABLES/ApplicationChart.tl")
(load "HTML/TABLES/CapabilityChart.tl")
(load "HTML/TABLES/DataChart.tl")
(load "HTML/TABLES/MainStrategyChart.tl")
(load "HTML/TABLES/NetworkChart.tl")
(load "HTML/TABLES/ObjectiveChart.tl")
(load "HTML/TABLES/ProcessChart.tl")
(load "HTML/TABLES/ProjectChart.tl")
(load "HTML/TABLES/SAPChart.tl")
(load "HTML/TABLES/ServerChart.tl")
(load "HTML/TABLES/ServiceChart.tl")
(load "HTML/TABLES/VlanChart.tl")