[[
    //// Purpose: Generates html files for the table charts
    //// Purpose: Generates json files for the table charts
    //// loaded by: TL/CORE/GenerateReport
    
    (load "TL/TABLES/ApplicationChart.tl")
    (load "TL/JSON/TABLES/ApplicationChart.tl")

    (load "TL/TABLES/CapabilityChart.tl")
    (load "TL/JSON/TABLES/CapabilityChart.tl")

    (load "TL/TABLES/DataChart.tl")
    (load "TL/JSON/TABLES/DataChart.tl")

    (load "TL/TABLES/MainStrategyChart.tl")
    (load "TL/JSON/TABLES/MainStrategyChart.tl")
    
    (load "TL/TABLES/NetworkChart.tl")
    (load "TL/JSON/TABLES/NetworkChart.tl")

    (load "TL/TABLES/ObjectiveChart.tl")
    (load "TL/JSON/TABLES/ObjectiveChart.tl")

    (load "TL/TABLES/ProcessChart.tl")
    (load "TL/JSON/TABLES/ProcessChart.tl")

    (load "TL/TABLES/ProjectChart.tl")
    (load "TL/JSON/TABLES/ProjectChart.tl")

    (load "TL/TABLES/SAPChart.tl")
    (load "TL/JSON/TABLES/SAPChart.tl")

    (load "TL/TABLES/ServerChart.tl")
    (load "TL/JSON/TABLES/ServerChart.tl")

    (load "TL/TABLES/ServiceChart.tl")
    (load "TL/JSON/TABLES/ServiceChart.tl")

    (load "TL/TABLES/VlanChart.tl")
    (load "TL/JSON/TABLES/VlanChart.tl")
]]