[[
	(load "../../../../_common_tl/Diagram/DiagramsInstances.tl")
	////=============================================================================
	//// Generate Tree.
	////-----------------------------------------------------------------------------
	(load "../../../../_common_tl/Diagram/DiagramsTree.tl")
	(load "../../../../_common_tl/Diagram/TreeTitle.tl")
	(load "../../../../_common_tl/Diagram/CollapsedTree.tl")
]]