//// Purpose: Generates json files for the table charts
//// loaded by: TL/CORE/GenerateReport

(load "TL/JSON/TABLES/ApplicationChart.tl")
(load "TL/JSON/TABLES/CapabilityChart.tl")
(load "TL/JSON/TABLES/DataChart.tl")
(load "TL/JSON/TABLES/MainStrategyChart.tl")
(load "TL/JSON/TABLES/NetworkChart.tl")
(load "TL/JSON/TABLES/ObjectiveChart.tl")
(load "TL/JSON/TABLES/ProcessChart.tl")
(load "TL/JSON/TABLES/ProjectChart.tl")
(load "TL/JSON/TABLES/SAPChart.tl")
(load "TL/JSON/TABLES/ServerChart.tl")
(load "TL/JSON/TABLES/ServiceChart.tl")
(load "TL/JSON/TABLES/VlanChart.tl")