[[
    //// Purpose: Generates html files for the table charts
    //// loaded by: TL/CORE/GenerateReport
    (load "TL/TABLES/ApplicationChart.tl")
    (load "TL/TABLES/CapabilityChart.tl")
    (load "TL/TABLES/DataChart.tl")
    (load "TL/TABLES/MainStrategyChart.tl")
    (load "TL/TABLES/NetworkChart.tl")
    (load "TL/TABLES/ObjectiveChart.tl")
    (load "TL/TABLES/ProcessChart.tl")
    (load "TL/TABLES/ProjectChart.tl")
    (load "TL/TABLES/SAPChart.tl")
    (load "TL/TABLES/ServerChart.tl")
    (load "TL/TABLES/ServiceChart.tl")
    (load "TL/TABLES/VlanChart.tl")
]]