[[
//// **************************************************************************
//// Purpose to generate the Information related to the Policy concept
//// loaded by object.tl
//// **************************************************************************

(set Law $obj)
(set Articles $Law.$lawLglElmFunc)
(set Policies $Law.$lawActedByFunc)
(set TabSelected "../Images/TabSelected.png")
(set TabNormal "../Images/TabNormal.png")
]]