[[

//// **************************************************************************
//// Purpose to generate the Information related to the Perspective Theme concept
//// loaded by object.tl
//// **************************************************************************

//// to load the path and the outfile name

(set perspectiveTheme $obj)
(set PersTheme_Persp $perspectiveTheme.$perspthemeBelongsFunc)
(set PTheme_SM $perspectiveTheme.$themeStratMapFunc)
(set PTheme_Obj $perspectiveTheme.$themeObjvFunc)

]]