[[

(set name           $obj.$objNameFunc)
(set fac_name       $obj.$objNameFunc)
(set brand          $obj.$entIDFunc)
(set server_hosted  $obj.$PhySerHostOfFunc)
(set ServBreifDesc  $obj.$objDescFunc)
(set server_role    $obj.$networkServTypeFunc)
(set operating_sys  $obj.$compPlatOSFunc)
(set importance     $obj.$entBusSevFunc)
(set supplier       $obj.$entResSupplierFunc)
(set installed_app  $obj.$compPlatInstOnFunc)
(set site           $obj.$capPerformedAtFunc)
(set IP_addr        $obj.$networkNodeIPFunc)
(set dep_date       $obj.$entAcqDateFunc)
(set server_price   $obj.$entPurchaseCostFunc)
(set server_maint   $obj.$entMaintenanceCostFunc)

(load "HTML/INFO/server.html")
]]


