[[






(set name $obj.$name_func)
(set fac_name $obj.$name_func)
(set brand $obj.$modelName_func)
(set server_hosted $obj.$HostOf_func)
(set Server_breifDescription $obj.$description_func)
(set server_role $obj.$serverType_func)
(set operating_sys $obj.$OS_func)
(set importance $obj.$businessSeverity_func)
(set supplier $obj.$supplier_func)
(set installed_app $obj.$installedOn_func)
(set site $obj.$performedAt_func)
(set IP_addr $obj.$IP_func)
(set dep_date $obj.$depDate_func2)
(set server_price $obj.$purchase_func)
(set server_maint $obj.$maintenance_func)

(load "HTML/INFO/server.html")
]]


