[[






(set name $obj.$name_func)
(set fac_name $obj.$name_func)
(set brand $obj.$entIDFunc)
(set server_hosted $obj.$PhySerHostOfFunc)
(set Server_breifDescription $obj.$description_func)
(set server_role $obj.$networkServerTypeFunc)
(set operating_sys $obj.$compPlatOSFunc)
(set importance $obj.$entBusSevFunc)
(set supplier $obj.$entResSupplierFunc)
(set installed_app $obj.$compPlatInstOnFunc)
(set site $obj.$capPerformedAtFunc)
(set IP_addr $obj.$networkNodeIPFunc)
(set dep_date $obj.$entAcqDateFunc)
(set server_price $obj.$entPurchaseCostFunc)
(set server_maint $obj.$entMaintenanceCostFunc)

(load "HTML/INFO/server.html")
]]


