[[
//// **************************************************************************
//// Purpose to generate the Information related to the Perspective Theme concept
//// loaded by object.tl
//// **************************************************************************

//// to load the outfile name

(set Strategy $obj)
(set Strategy_obj $Strategy.*STRATEGY::objectives)
(set Strategy_barr $Strategy.*STRATEGY::barriers)
(set Strategy_super $Strategy.*STRATEGY::superstrategies)
(set Strategy_sub $Strategy.*STRATEGY::substrategies)

]]