[[

//// **************************************************************************
//// Purpose to generate the Information related to the Perspective Theme concept
//// loaded by object.tl
//// **************************************************************************

//// to load the path and the outfile name

(set perspectiveTheme $obj)
(set PersTheme_Persp $perspectiveTheme.$PersTheme_Persp_func)
(set PTheme_SM $perspectiveTheme.$PTheme_SM_func)
(set PTheme_Obj $perspectiveTheme.$PTheme_Obj_func)

]]